### ISSUE TITLE
RFE: Add progress bar to "saving" panel

### ISSUE THREAD

**Issue by matthew-cline** [RoboPhred/oni-duplicity#1]
It would be nice if the "saving" panel had a progress bar instead of a spinner.

**Comment by RoboPhred** [comment]
I started working on this, but trying to ship progress info across from the webworker is taking an oddly significant amount of time away from both loading and saving.  The actual reporting being done by oni-save-parser does not affect performance at all, so I suspect its something to do with the link between the webworker thread and the main browser thread.

**Comment by RoboPhred** [comment]
So this was in place and mostly functional, but had a big hit on performance.  The feature has since been made inoperable due the redesign of oni-save-parser to support the CU.  The redesign was made in a way that can support this, but it is not compatible as a drop-in replacement for the old version.

  This feature has been pushed out, but is still on my list of things to do.

**Comment by RoboPhred** [comment]
Added in v2
