### ISSUE TITLE
Adding Things in Raw Editor

### ISSUE THREAD

**Issue by strau0106** [RoboPhred/oni-duplicity#107]
You can't add things to the Raw Editor nor deleting. Kinda cool if that was added

**Comment by andr9528** [comment]
Being able to remove with the Raw editor would possibly mean that you would be able to turn off MeteorShowers. I have been playing with Baator in Spaced Out! To disable Baator from adding meteors to a Asteroid you'd simply have to comment out the following lines from Baator.yaml file, by placing a 'hashtag' before each line.

> seasons:
> - MeteorShowers

Removing the one from the image below, should in theory disable MeteorShowers for the selected Asteroid.
![image](https://user-images.githubusercontent.com/21788044/134816664-87103b02-688f-41b5-b568-6090572e373d.png)

Due to bugs with my mods in general, my Baator.yaml file had reset, causing Meteors to spawn with my new asteroid, which i didn't have on my previous run with Baator.
