### ISSUE TITLE
Save Version 7.31

### ISSUE THREAD

**Issue by JLB222** [RoboPhred/oni-duplicity#136]
**_Save version "7.31" is not compatible with this parser. Expected version "7.25"._**

Are you able/willing to update for the latest major game update, "Hot Shots"?

Thank you in advance, and thank you for all the mileage I've already gotten out of your editor over the last few years!

Edit:  I should clarify:  The thing that doesn't seem to be working is the Duplicant screen.  I just get a blank white page.

**Comment by OriginalFoamy** [comment]
Can confirm, I get the same results. This editor is, for me, the only thing that makes the game playable.

**Comment by gamerCat898** [comment]
I tried to use Duplicity after DGSM broke, but after seeing that this broke too, now I'm stuck. please update this! At least make it so that the Duplicant screen works.

**Comment by Celelste** [comment]
Still an issue in late Feb. 2023

**Comment by OriginalFoamy** [comment]
Still an issue in March 2023. Dude is dead or this is abandoned completely. RIP Duplicity.

**Comment by StriateCash** [comment]
I've found myself facing this issue as well. I decided to make a new colony because I haven't played in a while, but since DGSM doesn't seem to work anymore I just decided to get my dupes selected and come here to edit them. The most I've done on the save file is set the priorities and the schedule, I've also set some dig commands, but I don't see how any of that would affect the editor. I also have all original dupes, so unlike last time I commented that shouldn't be an issue either. I'm sure it's an issue with the editor not being compatible with the current game update, but I sadly am not good enough with coding to fix the issue myself.
That all being said, I have attached my save file below just in case it helps you resolve the issue. I suspect that you're likely busy with other things and I do hope that you find a solution to all of that. And that being said, I don't expect you to fix this issue until you have the time to do so. This is likely a project you're not getting paid to work on and I respect that you've worked on it so much already, so please, take your time when it comes to fixing it, should you decide to. But until then, do take care and stay safe.
Here is the save file.
https://drive.google.com/drive/folders/1Ctgpo7OZblk0f48Sv6VJk5QAxN1UQG3C?usp=share_link

**Comment by thatfrozenfrog** [comment]
> I've found myself facing this issue as well. I decided to make a new colony because I haven't played in a while, but since DGSM doesn't seem to work anymore I just decided to get my dupes selected and come here to edit them. The most I've done on the save file is set the priorities and the schedule, I've also set some dig commands, but I don't see how any of that would affect the editor. I also have all original dupes, so unlike last time I commented that shouldn't be an issue either. I'm sure it's an issue with the editor not being compatible with the current game update, but I sadly am not good enough with coding to fix the issue myself. That all being said, I have attached my save file below just in case it helps you resolve the issue. I suspect that you're likely busy with other things and I do hope that you find a solution to all of that. And that being said, I don't expect you to fix this issue until you have the time to do so. This is likely a project you're not getting paid to work on and I respect that you've worked on it so much already, so please, take your time when it comes to fixing it, should you decide to. But until then, do take care and stay safe. Here is the save file. https://drive.google.com/drive/folders/1Ctgpo7OZblk0f48Sv6VJk5QAxN1UQG3C?usp=share_link

Well first, thanks for the .sav file. I'm just curious what version is it

**Comment by RoboPhred** [comment]
I do not have time to update this project, and I have not been involved in ONI for quite some time now.

That being said, I was able to take your save file and use it to fix the editor crash when editing duplicants.  However, this does not mean the editor is now working.  
It can edit files just fine, but it has not been updated since Spaced Out came out, and there is no guarantee that it will not corrupt save files.
Among other things, the editor can now no longer edit the body of the duplicant, since that system has changed.  I have disabled the editor for bodies since that's what was crashing, but other changes might not cause the editor to crash, and such changes are very likely to cause the game itself to crash when trying to handle the save.

At any rate, I have done what I can to keep this thing from dying.  I have left a message in the editor calling for anyone who has the skillset (React/Typescript) to check out the repo and see about either taking over mantainership, or starting fresh from my original save parser (which seems to still be completely up to date, as nothing about the save encoding has changed).  If anyone wants to take over this project I will gladly provide assistance where I can.
