### ISSUE TITLE
Bringing a Dupe back to life

### ISSUE THREAD

**Issue by lfricken** [RoboPhred/oni-duplicity#45]
I tried bringing a duplicant back to life with the editor (they suffocated). I raised their oxygen to 100%,  but their status is marked as "Perfect" as opposed to Dead in the editor already and I tried modifying it. How can you revive a duplicant with the editor?

**Comment by CombatVolcano** [comment]
I also would like to know this

**Comment by RoboPhred** [comment]
I think a lot of this lies inside the AI state machine, which is quite complex.  I suspect there might be too much info required by a "living" dup that gets erased when they die.

All this will have to wait until I get around to reverse engineering the StateMachine data though.

**Comment by RoboPhred** [comment]
I did a few experiments and was able to resurrect a duplicant by deleting their state machine, essentially lobotomizing them.  The issue is this completely blows away their api, and might result in unpredictable weirdness given that the rest of the game is already set up for considering them dead.

There is the `Clone` option now, which does something very similar, but into a brand new duplicant.  While this isn't without its issues (cloned duplicants use the same bed as their originals), it is at least enough to recover the traits and appearance of the lost duplicant.

**Comment by RoboPhred** [comment]
I am going to leave the `Clone` method as the solution to this, as modifying the state machine to resurrect the duplicant is too fragile.
