### ISSUE TITLE
RFE: export and import duplicants

### ISSUE THREAD

**Issue by matthew-cline** [RoboPhred/oni-duplicity#8]
There should be a way to export a dupe to JSON then import the JSON back in (either replacing an existing dupe or adding a new one).  The use case I have in mind is putting up a tutorial save based on a particular seed.  When a new release comes out with new terrain/biomes/critters/etc the save file can be recreated from the seed, then the starting duplicants from the old save can be transferred to the new one.  Another use case would be external utilities modifying and creating duplicants.

**Comment by RoboPhred** [comment]
This is a great idea!  While I won't be able to exactly duplicate the duplicant, I can export the data I do know about, allowing for sets of skills / appearance / traits / whatnot to be applied to existing dups.

I cannot (yet) create new duplicants since the editor does not yet understand 100% of their data yet.  I am reasonably sure some of the dups hold references to other objects or map specific info, such as what they are currently tasked with or information linked with the daily reports.

Implementing this is a bit difficult with the current design, but the parser is getting a rework which should allow the site to edit the save object directly.  This should let me make a general-purpose "export/import" data tool hanging off any game object behavior.

For external tools, you can use the underlying [oni-save-parser](https://github.com/RoboPhred/oni-save-parser) library directly.  It's licensed under MIT, so you can embed it anywhere you need it (just make sure to include the license notice).

**Comment by RoboPhred** [comment]
Importing / Exporting duplicants is now in the master branch, and live on /vnext
