### ISSUE TITLE
Attribute values not saving

### ISSUE THREAD

**Issue by Thorworx** [RoboPhred/oni-duplicity#81]
Any changes to dupe attribute values are not saving consistently in Firefox.
It take several entries and/or switching between screens to make the values stick.
May or may not be related error in console:

`Source map error: request failed with status 404 Resource URL: https://robophred.github.io/oni-duplicity/vendors~client.952d1488ea762c604573.bundle.js Source Map URL: vendors~client.952d1488ea762c604573.bundle.js.map`

Presumably the form fields are using an onChange event? Not sure why values aren't being updated.

**Comment by RoboPhred** [comment]
The fields actually use onBlur / onKeyPress with enter key in order to commit their value.  The issue is onChange would update with each keystroke, which would turn the value into a number and back.  That would prevent things like editing decimals or negative values.

The component it uses is [here](https://github.com/RoboPhred/oni-duplicity/blob/master/src/components/CommitTextField/component.tsx).

The field should update the backing store when you click off of it or when you click enter.  Perhaps there is a case where switching screens does not trigger onBlur?  Can you give me a step by step set of instructions to reproduce this?

**Comment by Thorworx** [comment]
1) Load example save
2) Click Duplicants
3) Click pencil to edit duplicant attribute
4) Change value using arrows
5) Click back arrow (top menu) to return to Duplicant screen
Result: change is not saved/ file is not marked as modified.

Did a couple more tests...
Typing numbers and hitting enter (or clicking a different field) works. Using only arrows does not.

**Comment by RoboPhred** [comment]
Thanks, I set the field up to commit the value on unload, so that should take care of values not being set if you change the page without unfocusing them.
